--Grant pro uživatele student.
GRANT SELECT ON DODAVATEL TO STUDENT;
GRANT SELECT on KONTO TO STUDENT;
GRANT SELECT on NAKUP TO STUDENT;
GRANT SELECT on NAKUP_ZBOZI TO STUDENT;
GRANT SELECT on STRAVNIK TO STUDENT;
GRANT SELECT on ZBOZI TO STUDENT;

--Grant pro uživatele IT218
GRANT SELECT, INSERT, UPDATE, DELETE ON DODAVATEL TO DB4IT218;
GRANT SELECT, INSERT, UPDATE, DELETE ON KONTO TO DB4IT218;
GRANT SELECT, INSERT, UPDATE, DELETE ON NAKUP TO DB4IT218;
GRANT SELECT, INSERT, UPDATE, DELETE ON NAKUP_ZBOZI TO DB4IT218;
GRANT SELECT, INSERT, UPDATE, DELETE ON STRAVNIK TO DB4IT218;
GRANT SELECT, INSERT, UPDATE, DELETE ON ZBOZI TO DB4IT218;